image: node:latest

stages:
  - install
  - build
  - deploy

install:
  stage: install
  script: 
    -apt-get upgrade -qq && apt-get install
    -yarn config set cache-folder .yarn
    -yarn install
  artifacts:
    name : "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .yarn/
      - node_modules/
    rules:
      - if: $CI_COMMIT_REF_NAME == "master"
        when: always
      -if : $CI_COMMIT_REQUEST_TARGET_BRANCH_NAME == "master"
        when: always
      -when: never




build:
  stage: build
  dependencies:
    -install
  scipt:
    -yarn build
  artifacts:
    name : "artifacts"
    paths:
      - .yarn/
      - node_modules/
    rules:
      - if: $CI_COMMIT_REF_NAME == "master"
        when: always
      -if : $CI_COMMIT_REQUEST_TARGET_BRANCH_NAME == "master"
        when: always
      -when: never


deploy:
  stage: deploy